apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: {{.Values.domain}}
spec:
    secretName: {{.Values.certName}}
    issuerRef:
        name: letsencrypt
    commonName: {{.Values.domain}}
    dnsNames:
        - {{.Values.domain}}